/**
 * Drizzle schema DRAFT for review (kickoff, 2026-09-28).
 *
 * Not compiled by the app. In Phase 1 (task 1.7) the Phase 0–1 sections move
 * into src/server/db/schema/*.ts. Later sections move in with their phase, so
 * each phase's migration only adds its own tables.
 *
 * Conventions
 * - Our ids are uuid, generated in the app (UUIDv7, often on the client).
 * - Better Auth ids are text; FKs to `user.id` are therefore text.
 * - Money is bigint minor units, read as JS number (assertMinor at boundaries).
 * - All timestamps are timestamptz.
 */
import { sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  char,
  check,
  date,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  primaryKey,
  smallint,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';

// Shared column helpers ------------------------------------------------------

const money = (name: string) => bigint(name, { mode: 'number' });
const currency = (name: string) => char(name, { length: 3 });
const createdAt = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
const updatedAt = () => timestamp('updated_at', { withTimezone: true }).notNull().defaultNow();
const tstz = (name: string) => timestamp(name, { withTimezone: true });

// Types owned by src/lib/money and src/lib/contracts (placeholders here) -----

type SplitInput = { type: string } & Record<string, unknown>;
type EntrySnapshot = Record<string, unknown>;
type ActivityData = Record<string, unknown>;

// ============================================================================
// Phase 0 — Better Auth (generated by `@better-auth/cli generate`; shown so
// FKs type-check). session / account / verification are generated alongside.
// ============================================================================

export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').notNull().default(false),
  image: text('image'),
  isAnonymous: boolean('is_anonymous').notNull().default(false), // anonymous plugin
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

// ============================================================================
// Phase 1 — groups, members, ledger
// ============================================================================

export const groupType = pgEnum('group_type', ['trip', 'home', 'couple', 'other', 'direct']);
export const memberRole = pgEnum('member_role', ['owner', 'member']);
export const entryKind = pgEnum('entry_kind', ['expense', 'settlement', 'opening_balance']);
export const splitType = pgEnum('split_type', [
  'equal',
  'exact',
  'percentage',
  'shares',
  'adjustment',
  'itemized',
  'imported_net',
]);
export const entrySource = pgEnum('entry_source', ['app', 'splitwise_import', 'recurring']);
export const settlementMethod = pgEnum('settlement_method', ['cash', 'upi', 'bank', 'other']);
export const revisionReason = pgEnum('revision_reason', ['edit', 'delete', 'restore', 'conflict']);

export const groups = pgTable(
  'groups',
  {
    id: uuid('id').primaryKey(),
    name: varchar('name', { length: 60 }).notNull(),
    type: groupType('type').notNull().default('other'),
    defaultCurrency: currency('default_currency').notNull().default('INR'),
    simplifyDebts: boolean('simplify_debts').notNull().default(true),
    inviteCode: text('invite_code').notNull(), // 128-bit random, base64url; rotatable
    inviteExpiresAt: tstz('invite_expires_at'),
    // type = 'direct' only: sorted "userA:userB" once both members are real users
    directKey: text('direct_key'),
    createdByUserId: text('created_by_user_id').references(() => user.id, { onDelete: 'set null' }),
    lastActivityAt: tstz('last_activity_at').notNull().defaultNow(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex('groups_invite_code_uq').on(t.inviteCode),
    uniqueIndex('groups_direct_key_uq').on(t.directKey).where(sql`${t.directKey} IS NOT NULL`),
    check('groups_currency_ck', sql`${t.defaultCurrency} ~ '^[A-Z]{3}$'`),
  ],
);

export const groupMembers = pgTable(
  'group_members',
  {
    id: uuid('id').primaryKey(),
    groupId: uuid('group_id')
      .notNull()
      .references(() => groups.id, { onDelete: 'cascade' }),
    // null = placeholder ("Ravi — not joined yet"); anonymous user = guest
    userId: text('user_id').references(() => user.id, { onDelete: 'set null' }),
    displayName: varchar('display_name', { length: 40 }).notNull(),
    role: memberRole('role').notNull().default('member'),
    claimTokenHash: text('claim_token_hash'), // sha256 of a single-use token
    claimTokenExpiresAt: tstz('claim_token_expires_at'),
    joinedAt: tstz('joined_at'), // null until someone joins/claims this spot
    removedAt: tstz('removed_at'), // soft remove; only at zero balance
    createdAt: createdAt(),
  },
  (t) => [
    index('group_members_group_idx').on(t.groupId),
    index('group_members_user_idx').on(t.userId),
    uniqueIndex('group_members_active_user_uq')
      .on(t.groupId, t.userId)
      .where(sql`${t.userId} IS NOT NULL AND ${t.removedAt} IS NULL`),
    uniqueIndex('group_members_claim_token_uq')
      .on(t.claimTokenHash)
      .where(sql`${t.claimTokenHash} IS NOT NULL`),
  ],
);

export const entries = pgTable(
  'entries',
  {
    id: uuid('id').primaryKey(), // client-generated UUIDv7; also the rounding seed
    groupId: uuid('group_id')
      .notNull()
      .references(() => groups.id, { onDelete: 'cascade' }),
    kind: entryKind('kind').notNull(),
    description: varchar('description', { length: 120 }).notNull(),
    category: varchar('category', { length: 32 }), // key from src/lib/categories
    amount: money('amount').notNull(),
    currency: currency('currency').notNull(),
    // Phase 3: set only when a user explicitly converts an expense
    originalAmount: money('original_amount'),
    originalCurrency: currency('original_currency'),
    fxRate: numeric('fx_rate', { precision: 20, scale: 10 }),
    fxDate: date('fx_date'),
    fxSource: text('fx_source'),
    date: date('date').notNull(), // calendar date as the user sees it
    notes: varchar('notes', { length: 1000 }),
    splitType: splitType('split_type').notNull(),
    splitInput: jsonb('split_input').$type<SplitInput>().notNull(), // canonical, versioned input
    settlementMethod: settlementMethod('settlement_method'), // kind = 'settlement' only
    createdByMemberId: uuid('created_by_member_id')
      .notNull()
      .references(() => groupMembers.id),
    updatedByMemberId: uuid('updated_by_member_id').references(() => groupMembers.id),
    source: entrySource('source').notNull().default('app'),
    importId: uuid('import_id'), // FK to imports added in Phase 2
    importRowHash: text('import_row_hash'),
    recurringRuleId: uuid('recurring_rule_id'), // FK to recurring_rules added in Phase 3
    recurringPeriod: text('recurring_period'), // e.g. '2026-10'
    version: integer('version').notNull().default(1),
    deletedAt: tstz('deleted_at'),
    deletedByMemberId: uuid('deleted_by_member_id').references(() => groupMembers.id),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index('entries_group_live_date_idx').on(t.groupId, t.deletedAt, t.date.desc()),
    index('entries_group_creator_idx').on(t.groupId, t.createdByMemberId, t.createdAt.desc()),
    uniqueIndex('entries_import_row_uq')
      .on(t.groupId, t.importRowHash)
      .where(sql`${t.importRowHash} IS NOT NULL`),
    uniqueIndex('entries_recurring_period_uq')
      .on(t.recurringRuleId, t.recurringPeriod)
      .where(sql`${t.recurringRuleId} IS NOT NULL`),
    check('entries_amount_ck', sql`${t.amount} >= 0`),
    check('entries_currency_ck', sql`${t.currency} ~ '^[A-Z]{3}$'`),
    check(
      'entries_settlement_method_ck',
      sql`(${t.kind} = 'settlement') OR (${t.settlementMethod} IS NULL)`,
    ),
  ],
);

export const entryPayers = pgTable(
  'entry_payers',
  {
    entryId: uuid('entry_id')
      .notNull()
      .references(() => entries.id, { onDelete: 'cascade' }),
    memberId: uuid('member_id')
      .notNull()
      .references(() => groupMembers.id),
    amount: money('amount').notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.entryId, t.memberId] }),
    index('entry_payers_member_idx').on(t.memberId),
    check('entry_payers_amount_ck', sql`${t.amount} >= 0`),
  ],
);

export const entryShares = pgTable(
  'entry_shares',
  {
    entryId: uuid('entry_id')
      .notNull()
      .references(() => entries.id, { onDelete: 'cascade' }),
    memberId: uuid('member_id')
      .notNull()
      .references(() => groupMembers.id),
    amount: money('amount').notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.entryId, t.memberId] }),
    index('entry_shares_member_idx').on(t.memberId),
    check('entry_shares_amount_ck', sql`${t.amount} >= 0`),
  ],
);

export const entryRevisions = pgTable(
  'entry_revisions',
  {
    id: uuid('id').primaryKey(),
    entryId: uuid('entry_id')
      .notNull()
      .references(() => entries.id, { onDelete: 'cascade' }),
    version: integer('version').notNull(), // the version this snapshot captured
    snapshot: jsonb('snapshot').$type<EntrySnapshot>().notNull(), // entry + payers + shares (+ items)
    reason: revisionReason('reason').notNull(),
    actorMemberId: uuid('actor_member_id').references(() => groupMembers.id),
    createdAt: createdAt(),
  },
  (t) => [uniqueIndex('entry_revisions_entry_version_uq').on(t.entryId, t.version)],
);

export const comments = pgTable(
  'comments',
  {
    id: uuid('id').primaryKey(),
    groupId: uuid('group_id')
      .notNull()
      .references(() => groups.id, { onDelete: 'cascade' }), // denormalised for authz
    entryId: uuid('entry_id')
      .notNull()
      .references(() => entries.id, { onDelete: 'cascade' }),
    authorMemberId: uuid('author_member_id')
      .notNull()
      .references(() => groupMembers.id),
    body: varchar('body', { length: 1000 }).notNull(),
    deletedAt: tstz('deleted_at'),
    createdAt: createdAt(),
  },
  (t) => [index('comments_entry_idx').on(t.entryId, t.createdAt)],
);

export const activity = pgTable(
  'activity',
  {
    id: uuid('id').primaryKey(), // UUIDv7 → time-ordered
    groupId: uuid('group_id')
      .notNull()
      .references(() => groups.id, { onDelete: 'cascade' }),
    actorMemberId: uuid('actor_member_id').references(() => groupMembers.id),
    // entry_created | entry_updated | entry_deleted | entry_restored | settlement_recorded
    // member_joined | member_claimed | member_reclaimed | member_removed | invite_rotated
    // group_updated | comment_added | import_completed | recurring_created
    kind: varchar('kind', { length: 32 }).notNull(),
    entryId: uuid('entry_id').references(() => entries.id, { onDelete: 'set null' }),
    data: jsonb('data').$type<ActivityData>().notNull().default({}),
    createdAt: createdAt(),
  },
  (t) => [index('activity_group_idx').on(t.groupId, t.createdAt.desc())],
);

export const idempotencyKeys = pgTable(
  'idempotency_keys',
  {
    userId: text('user_id').notNull(),
    key: uuid('key').notNull(), // = client mutation id
    requestHash: text('request_hash').notNull(), // same key + different body → 422
    statusCode: smallint('status_code'), // null while in flight
    response: jsonb('response'),
    createdAt: createdAt(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.key] }), index('idempotency_created_idx').on(t.createdAt)],
);

export const rateLimitBuckets = pgTable(
  'rate_limit_buckets',
  {
    key: text('key').notNull(), // e.g. 'join:ip:1.2.3.4'
    windowStart: tstz('window_start').notNull(),
    count: integer('count').notNull().default(0),
  },
  (t) => [primaryKey({ columns: [t.key, t.windowStart] })],
);

// ============================================================================
// Phase 2 — Splitwise import
// ============================================================================

export const importStatus = pgEnum('import_status', ['previewed', 'completed', 'failed']);

export const imports = pgTable(
  'imports',
  {
    id: uuid('id').primaryKey(),
    groupId: uuid('group_id')
      .notNull()
      .references(() => groups.id, { onDelete: 'cascade' }),
    source: varchar('source', { length: 32 }).notNull().default('splitwise_csv'),
    fileHash: text('file_hash').notNull(),
    fileName: varchar('file_name', { length: 200 }),
    status: importStatus('status').notNull(),
    report: jsonb('report').notNull(), // rows, duplicates, invalid rows, verification diff
    createdByMemberId: uuid('created_by_member_id').references(() => groupMembers.id),
    createdAt: createdAt(),
  },
  (t) => [index('imports_group_idx').on(t.groupId)],
);

// ============================================================================
// Phase 3 — itemized, recurring, receipts, FX, push
// ============================================================================

export const entryItems = pgTable(
  'entry_items',
  {
    id: uuid('id').primaryKey(),
    entryId: uuid('entry_id')
      .notNull()
      .references(() => entries.id, { onDelete: 'cascade' }),
    position: smallint('position').notNull(),
    name: varchar('name', { length: 80 }).notNull(),
    amount: money('amount').notNull(),
  },
  (t) => [index('entry_items_entry_idx').on(t.entryId), check('entry_items_amount_ck', sql`${t.amount} >= 0`)],
);

export const entryItemAssignees = pgTable(
  'entry_item_assignees',
  {
    itemId: uuid('item_id')
      .notNull()
      .references(() => entryItems.id, { onDelete: 'cascade' }),
    memberId: uuid('member_id')
      .notNull()
      .references(() => groupMembers.id),
    weight: integer('weight').notNull().default(1),
  },
  (t) => [primaryKey({ columns: [t.itemId, t.memberId] }), check('entry_item_weight_ck', sql`${t.weight} > 0`)],
);

export const recurringRules = pgTable(
  'recurring_rules',
  {
    id: uuid('id').primaryKey(),
    groupId: uuid('group_id')
      .notNull()
      .references(() => groups.id, { onDelete: 'cascade' }),
    template: jsonb('template').notNull(), // entry payload minus id/date
    schedule: jsonb('schedule').notNull(), // { freq: 'monthly', dayOfMonth: 1 } | { freq: 'weekly', weekday: 1 }
    nextRunAt: tstz('next_run_at').notNull(),
    active: boolean('active').notNull().default(true),
    createdByMemberId: uuid('created_by_member_id').references(() => groupMembers.id),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('recurring_due_idx').on(t.active, t.nextRunAt)],
);

export const ocrStatus = pgEnum('ocr_status', ['none', 'pending', 'done', 'failed']);

export const receipts = pgTable(
  'receipts',
  {
    id: uuid('id').primaryKey(),
    groupId: uuid('group_id')
      .notNull()
      .references(() => groups.id, { onDelete: 'cascade' }),
    entryId: uuid('entry_id').references(() => entries.id, { onDelete: 'set null' }),
    uploadedByMemberId: uuid('uploaded_by_member_id').references(() => groupMembers.id),
    storageKey: text('storage_key').notNull(), // R2 object key
    bytes: integer('bytes').notNull(),
    contentType: varchar('content_type', { length: 64 }).notNull(),
    ocrStatus: ocrStatus('ocr_status').notNull().default('none'),
    ocrJson: jsonb('ocr_json'),
    createdAt: createdAt(),
  },
  (t) => [index('receipts_entry_idx').on(t.entryId)],
);

export const fxRates = pgTable(
  'fx_rates',
  {
    date: date('date').notNull(),
    base: currency('base').notNull(),
    quote: currency('quote').notNull(),
    source: varchar('source', { length: 32 }).notNull(), // 'ecb' | 'er-api' | 'manual'
    rate: numeric('rate', { precision: 20, scale: 10 }).notNull(),
    fetchedAt: createdAt(),
  },
  (t) => [primaryKey({ columns: [t.date, t.base, t.quote, t.source] })],
);

export const pushSubscriptions = pgTable(
  'push_subscriptions',
  {
    id: uuid('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    endpoint: text('endpoint').notNull(),
    keys: jsonb('keys').notNull(), // { p256dh, auth }
    createdAt: createdAt(),
  },
  (t) => [uniqueIndex('push_endpoint_uq').on(t.endpoint)],
);

// ============================================================================
// Phase 4 — monetisation
// ============================================================================

export const subjectType = pgEnum('subject_type', ['user', 'group']);
export const entitlementSource = pgEnum('entitlement_source', [
  'subscription',
  'trip_pass',
  'trial',
  'lifetime',
  'promo',
]);

export const entitlements = pgTable(
  'entitlements',
  {
    id: uuid('id').primaryKey(),
    subjectType: subjectType('subject_type').notNull(),
    subjectId: text('subject_id').notNull(), // user.id (text) or groups.id (uuid as text)
    plan: varchar('plan', { length: 32 }).notNull().default('plus'),
    source: entitlementSource('source').notNull(),
    sourceRef: text('source_ref'), // subscription id / payment id / promo code
    startsAt: tstz('starts_at').notNull(),
    endsAt: tstz('ends_at'), // null = lifetime
    revokedAt: tstz('revoked_at'),
    createdAt: createdAt(),
  },
  (t) => [index('entitlements_subject_idx').on(t.subjectType, t.subjectId, t.endsAt)],
);

export const subscriptions = pgTable(
  'subscriptions',
  {
    id: uuid('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id),
    provider: varchar('provider', { length: 16 }).notNull().default('razorpay'),
    providerSubscriptionId: text('provider_subscription_id').notNull(),
    planKey: varchar('plan_key', { length: 32 }).notNull(), // 'plus_monthly' | 'plus_annual'
    status: varchar('status', { length: 24 }).notNull(), // mirrors provider state
    currentPeriodEnd: tstz('current_period_end'),
    cancelAtPeriodEnd: boolean('cancel_at_period_end').notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex('subscriptions_provider_uq').on(t.provider, t.providerSubscriptionId)],
);

export const payments = pgTable(
  'payments',
  {
    id: uuid('id').primaryKey(),
    provider: varchar('provider', { length: 16 }).notNull().default('razorpay'),
    providerEventId: text('provider_event_id').notNull(), // webhook idempotency
    kind: varchar('kind', { length: 32 }).notNull(), // 'subscription_charge' | 'trip_pass' | 'lifetime' | 'refund'
    userId: text('user_id').references(() => user.id),
    groupId: uuid('group_id').references(() => groups.id),
    amount: money('amount'),
    currency: currency('currency'),
    raw: jsonb('raw').notNull(),
    createdAt: createdAt(),
  },
  (t) => [uniqueIndex('payments_event_uq').on(t.provider, t.providerEventId)],
);

export const usageCounters = pgTable(
  'usage_counters',
  {
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    feature: varchar('feature', { length: 32 }).notNull(), // 'ai_scan' | 'ai_quick_add'
    period: varchar('period', { length: 10 }).notNull(), // '2026-10' or '2026-10-05'
    count: integer('count').notNull().default(0),
  },
  (t) => [primaryKey({ columns: [t.userId, t.feature, t.period] })],
);

export const upsellImpressions = pgTable(
  'upsell_impressions',
  {
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    day: date('day').notNull(),
    feature: varchar('feature', { length: 32 }).notNull(),
    createdAt: createdAt(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.day] })], // ≤ 1 per user per day
);

export const featureConfig = pgTable('feature_config', {
  key: varchar('key', { length: 64 }).primaryKey(), // 'price.plus_monthly', 'quota.ai_scan', 'flag.early_access'
  value: jsonb('value').notNull(),
  updatedAt: updatedAt(),
});
